name: "GitHub follower change event"
description: "To get follow and unfollow event, could run as a cron job"
author: "Soros Liu"
branding:
  icon: "user-check"
  color: "green"
inputs:
  myToken:
    description: "github personal access token"
    required: true
  notifyUnFollowEvent:
    description: "should notify unfollow event or not"
    required: false
    default: "false"
outputs:
  changed:
    description: "whether follower changed or not"
  shouldNotify:
    description: "skip notification when no change or first run"
  markdown:
    description: "markdown for follower change info"
  plainText:
    description: "plain text for follower change info"
  htmlFilePath:
    description: "path of html file for follower change info"
runs:
  using: "node16"
  main: "dist/index.js"
