name: "Check if follower change"
description: "run as cron job, get follow and unfollow event"
branding:
  icon: 'user-check'  
  color: 'green'
inputs:
  myToken:
    description: "github personal access token"
    required: true
outputs:
  changed:
    description: "whether follower changed or not"
  shouldNotify:
    description: "skip notification when no change or first run"
  markdown:
    description: "markdown for follower change info"
runs:
  using: "node12"
  main: "dist/index.js"
