name: "Check if follower change"
description: "run as cron job, get follow and unfollow event"
inputs:
  myToken:
    description: "github personal access token"
    required: true
outputs:
  changed:
    description: "whether follower changed or not"
  markdown:
    description: "markdown for follower change info"
runs:
  using: "node12"
  main: "dist/index.js"
