name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get follower change
        id: followerChange
        uses: ./
        with:
          myToken: ${{ secrets.MY_TOKEN }}
      - name: Get the output
        run: >
          printf "
          is changed: ${{ steps.followerChange.outputs.changed }}\n
          markdown:\n
          ${{ steps.followerChange.outputs.markdown }}
          "
      - name: email me
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Follower Change
          from: Follower Change Notifier
          to: ${{ secrets.MY_EMAIL }}
          html_body: ${{ steps.followerChange.outputs.markdown }}
          convert_markdown: true
