name: "test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get follower change
        id: followerChange
        uses: ./
        with:
          myToken: ${{ secrets.MY_TOKEN }}
          notifyUnFollowEvent: "true"
      - name: Get the output
        run: >
          printf "
          is changed: ${{ steps.followerChange.outputs.changed }}\n
          should notify: ${{ steps.followerChange.outputs.shouldNotify }}
          "
      - uses: actions/upload-artifact@v2
        with:
          name: follower-change-html
          path: ./**/email.html
