name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get follower change
        id: followerChange
        uses: ./
        with:
          myToken: ${{ secrets.MY_TOKEN }}
      - name: Get the output
        run: >
          printf "
          is changed: ${{ steps.followerChange.outputs.changed }}\n
          markdown:\n
          ${{ steps.followerChange.outputs.markdown }}
          "
