name: "test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get follower change
        id: followerChange
        uses: Sorosliu1029/follower-change@maizzle
        with:
          myToken: ${{ secrets.MY_TOKEN }}
          notifyUnFollowEvent: "true"
      - name: Get the output
        run: >
          echo "is changed: ${{ steps.followerChange.outputs.changed }}" &
          echo "should notify: ${{ steps.followerChange.outputs.shouldNotify }}" &
          echo "${{ steps.followerChange.outputs.markdown }}" > followerChange.md &
          echo "${{ steps.followerChange.outputs.html }}" > followerChange.html &
          echo "${{ steps.followerChange.outputs.plainText }}$" > followerChange.txt
      - uses: actions/upload-artifact@v2
        with:
          name: follower-change-file
          path: ./followerChange.*
